---
name: cache-trunk
on:
  pull_request:
  push:
    branches: [main]
    paths: [.trunk/trunk.yaml]
  workflow_dispatch:
  workflow_call:

permissions: read-all
# permission for job is actions-write

jobs:
  build-cache:
    name: Cache Trunk
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Trunk Check
        uses: trunk-io/trunk-action@4d5ecc89b2691705fd08c747c78652d2fc806a94 # v1
        with:
          check-mode: populate_cache_only
