---
name: cache-trunk
on:
  pull_request:
  push:
    branches: [main]
    paths: [.trunk/trunk.yaml]
  workflow_dispatch:
  workflow_call:

permissions: read-all
# permission for job is actions-write

jobs:
  build-cache:
    name: Cache Trunk
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Trunk Check
        uses: trunk-io/trunk-action@e1234e67a86010d61ddac8d8ebf4b783e2ffd2fa # v2.0.0
        with:
          check-mode: populate_cache_only
