---
# workflow to seperately push annotations and support both forked and standard workflows securely
# https://github.com/marketplace/actions/trunk-check
name: annotate-pr-with-lint-issues
on:
  workflow_run:
    workflows: ['lint']
    types: [completed]
  workflow_call:

jobs:
  trunk-annotate:
    name: trunk-annotate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@34242ec4eb8cf594887600f1f9b889e7c630ec18 # v1.1.9
        with:
          post-annotations: true # only for fork PRs
