---
# workflow to seperately push annotations and support both forked and standard workflows securely
# https://github.com/marketplace/actions/trunk-check
name: annotate-pr-with-lint-issues
on:
  workflow_run:
    workflows: ['lint']
    types: [completed]
  workflow_call:

jobs:
  trunk-annotate:
    name: trunk-annotate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@718b71fb3e4d83f6734f0c372d92ee7d4c9976d7 # v1.1.11
        with:
          post-annotations: true # only for fork PRs
