---
name: lint
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}-${{ github.action }}
#   cancel-in-progress: false
permissions:
  pull-requests: read
  contents: read
  checks: write
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout
    steps:
      - name: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: set-aqua-policy-if-file-exists
        run: |
          if [ -f aqua-policy.yaml ]; then
            echo "AQUA_POLICY_CONFIG=${GITHUB_WORKSPACE}/aqua-policy.yaml:${AQUA_POLICY_CONFIG}" >> $GITHUB_ENV
          else
            echo "👉 No aqua-policy.yaml file found, skipping setting AQUA_POLICY_CONFIG"
          fi
      - uses: aquaproj/aqua-installer@36dc5833b04eb63f06e3bb818aa6b7a6e6db99a9 # v2.1.2
        continue-on-error: true
        with:
          aqua_version: v2.10.1
          enable_aqua_install: true
          aqua_opts: '--tags lint' # if using aqua.yaml config any special items in your repo like Golangci-lint using tags so it only installs what's needed
        env:
          AQUA_LOG_LEVEL: debug
          AQUA_OPTS: ''
      - name: trunk-check
        uses: trunk-io/trunk-action@34242ec4eb8cf594887600f1f9b889e7c630ec18 # v1.1.9
        with:
          arguments: --github-annotate-new-only=true
