---
# workflow to seperately push annotations and support both forked and standard workflows securely
# https://github.com/marketplace/actions/trunk-check
name: annotate-pr-with-lint-issues
on:
  workflow_run:
    workflows: ['lint']
    types: [completed]
  workflow_call:

jobs:
  trunk-annotate:
    name: trunk-annotate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@4d5ecc89b2691705fd08c747c78652d2fc806a94 # v1.1.19
        with:
          post-annotations: true # only for fork PRs
