---
# workflow to seperately push annotations and support both forked and standard workflows securely
# https://github.com/marketplace/actions/trunk-check
name: annotate-pr-with-lint-issues
on:
  workflow_run:
    workflows: ['lint']
    types: [completed]
  workflow_call:

jobs:
  trunk-annotate:
    name: trunk-annotate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@75699af9e26881e564e9d832ef7dc3af25ec031b # v1.2.4
        with:
          post-annotations: true # only for fork PRs
