---
name: release
on:
  # push:
  #   tags:
  #     - 'v*'
  workflow_dispatch:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.action }}
  cancel-in-progress: false
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      # https://github.com/magnetikonline/action-golang-cache
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@797f193169d3c8ba6f60d90f50ecdadd2583fbd8 # tag=v3
        with:
          go-version-file: go.mod
      - name: set-aqua-policy-if-file-exists
        run: |
          if [ -f aqua-policy.yaml ]; then
            echo "AQUA_POLICY_CONFIG=${GITHUB_WORKSPACE}/aqua-policy.yaml:${AQUA_POLICY_CONFIG}" >> $GITHUB_ENV
          else
            echo "👉 No aqua-policy.yaml file found, skipping setting AQUA_POLICY_CONFIG"
          fi
      - uses: aquaproj/aqua-installer@36dc5833b04eb63f06e3bb818aa6b7a6e6db99a9 # v2.1.2
        with:
          aqua_version: v2.10.1
          # working_directory:
          aqua_opts: '--tags release'
        env:
          AQUA_LOG_LEVEL: debug

      - name: mage-tidy
        uses: magefile/mage-action@3b833fb24c0d19eed3aa760b9eb285b4b84f420f # v2
        with:
          version: latest
          args: init
      - name: docker-login
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          username: ${{ secrets.DSV_DOCKER_USERNAME }}
          password: ${{ secrets.DSV_DOCKER_PASSWORD }}
      - name: mage-release
        uses: magefile/mage-action@3b833fb24c0d19eed3aa760b9eb285b4b84f420f # v2
        with:
          version: latest
          args: release
        env:
          # GitHub sets this automatically
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.DSV_SLACK_CHANNEL }}
          SLACK_WEBHOOK: ${{ secrets.DSV_SLACK_WEBHOOK }}
          DOCKER_ORG: ${{ secrets.DSV_DOCKER_REGISTRY }}

      # - name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@ff11ca24a9b39f2d36796d1fbd7a4e39c182630a # renovate: tag=v3.1.0
      #   with:
      #     version: latest
      #     args: release --rm-dist
      #   env:
      #     # GitHub sets this automatically
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SLACK_CHANNEL: ${{ secrets.DSV_SLACK_CHANNEL }}
      #     SLACK_WEBHOOK: ${{ secrets.DSV_SLACK_WEBHOOK }}
      #     DOCKER_ORG: ${{ secrets.DSV_DOCKER_REGISTRY }}
