---
name: release
on:
  # push:
  #   tags:
  #     - 'v*'
  workflow_dispatch:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.action }}
  cancel-in-progress: false
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      # https://github.com/magnetikonline/action-golang-cache
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@fcca93e25c7fe3943de4d40c22d255d17f63e63b # v5
        with:
          go-version-file: go.mod
      - name: set-aqua-policy-if-file-exists
        run: |
          if [ -f aqua-policy.yaml ]; then
            echo "AQUA_POLICY_CONFIG=${GITHUB_WORKSPACE}/aqua-policy.yaml:${AQUA_POLICY_CONFIG}" >> $GITHUB_ENV
          else
            echo "👉 No aqua-policy.yaml file found, skipping setting AQUA_POLICY_CONFIG"
          fi
      - uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
        with:
          aqua_version: v2.42.2
          # working_directory:
          aqua_opts: '--tags release'
          policy_allow: true
        env:
          AQUA_LOG_LEVEL: debug

      - name: mage-tidy
        uses: magefile/mage-action@6f50bbb8ea47d56e62dee92392788acbc8192d0b # v3
        with:
          version: latest
          args: init
      - name: docker-login
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          username: ${{ secrets.DSV_DOCKER_USERNAME }}
          password: ${{ secrets.DSV_DOCKER_PASSWORD }}
      - name: mage-release
        uses: magefile/mage-action@6f50bbb8ea47d56e62dee92392788acbc8192d0b # v3
        with:
          version: latest
          args: release
        env:
          # GitHub sets this automatically
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.DSV_SLACK_CHANNEL }}
          SLACK_WEBHOOK: ${{ secrets.DSV_SLACK_WEBHOOK }}
          DOCKER_ORG: ${{ secrets.DSV_DOCKER_REGISTRY }}

      # - name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@ff11ca24a9b39f2d36796d1fbd7a4e39c182630a # renovate: tag=v3.1.0
      #   with:
      #     version: latest
      #     args: release --rm-dist
      #   env:
      #     # GitHub sets this automatically
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SLACK_CHANNEL: ${{ secrets.DSV_SLACK_CHANNEL }}
      #     SLACK_WEBHOOK: ${{ secrets.DSV_SLACK_WEBHOOK }}
      #     DOCKER_ORG: ${{ secrets.DSV_DOCKER_REGISTRY }}
