---
name: stale
on:
  schedule:
    - cron: 30 1 * * *
  workflow_call:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.action }}
  cancel-in-progress: true
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      # Config Options: https://github.com/actions/stale#list-of-input-options
      - uses: actions/stale@5ebf00ea0e4c1561e9b43a292ed34424fb1d4578 # tag=v6
        with:
          days-before-stale: 30
          days-before-close: 5
          stale-issue-message: 🤖 This has been flagged as stale. If it is still relevant please post an update with context, otherwise this will shortly be closed. _You can always reopen a closed issue. This is not a permanent delete._
          stale-pr-message: 🤖 This is being marked as stale due to no recent activity. Update to keep this open.
          stale-issue-label: stale-issue
          exempt-issue-labels: pinned, security
          exempt-pr-labels: pinned, security
          stale-pr-label: stale
          stale-issues-label: stale
          close-issue-label: stale
          close-pr-label: stale
          exempt-draft-pr: true
          delete-branch: false
          ignore-pr-updates: true # else renovate prs will never age out
